// Generated by scripts/build-server-runtimes.mjs from scripts/test-connectors-entry.mjs. Do not edit this artifact.
import Stripe from "stripe";
import { randomUUID } from "node:crypto";
//#region api/_lib/billing.js
var BillingError = class extends Error {
	constructor(statusCode, message) {
		super(message);
		this.statusCode = statusCode;
	}
};
function billingConfig(env = process.env) {
	if (!env.COVA_BILLING_MODE) return null;
	const mode = env.COVA_BILLING_MODE, live = mode === "live";
	if (live) {
		if (env.COVA_BILLING_LIVE_ENABLED !== "true" || env.VERCEL_ENV !== "production" || env.VERCEL_TARGET_ENV && env.VERCEL_TARGET_ENV !== "production") throw new BillingError(503, "Live billing is disabled in this environment.");
		if (!/^(sk|rk)_live_/.test(env.STRIPE_SECRET_KEY || "")) throw new BillingError(503, "A live Stripe key is required.");
		if (!/^whsec_/.test(env.STRIPE_WEBHOOK_SECRET || "")) throw new BillingError(503, "Live billing webhook is not configured.");
	} else {
		if (mode !== "sandbox" || env.VERCEL_ENV === "production" || env.VERCEL_TARGET_ENV === "production") throw new BillingError(503, "Billing is disabled in this environment.");
		if (!/^(sk|rk)_test_/.test(env.STRIPE_SECRET_KEY || "")) throw new BillingError(503, "A sandbox Stripe key is required.");
	}
	const allowedUsers = new Set(String(env.COVA_BILLING_ALLOWED_USERS || "").split(",").map((v) => v.trim()).filter((v) => /^[0-9a-f-]{36}$/i.test(v)));
	if (!live && !allowedUsers.size) throw new BillingError(503, "A sandbox owner allowlist is required.");
	let origin;
	try {
		origin = new URL(env.COVA_BILLING_ORIGIN);
	} catch {
		throw new BillingError(503, "Billing origin is not configured.");
	}
	if (origin.protocol !== "https:" || origin.username || origin.password || origin.pathname !== "/" || origin.search || origin.hash || (live ? origin.origin !== "https://covadesk.com" : ["covadesk.com", "www.covadesk.com"].includes(origin.hostname))) throw new BillingError(503, live ? "Use the canonical live billing origin." : "Use an isolated HTTPS billing preview.");
	if (!/^acct_[a-zA-Z0-9]+$/.test(env.STRIPE_ACCOUNT_ID || "") || !/^price_[a-zA-Z0-9]+$/.test(env.STRIPE_PRO_PRICE_ID || "") || !/^bpc_[a-zA-Z0-9]+$/.test(env.STRIPE_PORTAL_CONFIGURATION_ID || "")) throw new BillingError(503, "Billing is not configured.");
	return {
		mode,
		amount: live ? 2900 : 3e3,
		allowedUsers,
		origin: origin.origin,
		accountId: env.STRIPE_ACCOUNT_ID,
		priceId: env.STRIPE_PRO_PRICE_ID,
		portalId: env.STRIPE_PORTAL_CONFIGURATION_ID,
		key: env.STRIPE_SECRET_KEY,
		webhookSecret: env.STRIPE_WEBHOOK_SECRET || ""
	};
}
function stripeClient(config) {
	return new Stripe(config.key, {
		apiVersion: "2026-08-26.dahlia",
		maxNetworkRetries: 1,
		timeout: 1e4
	});
}
function billingOwnerEnabled(config, owner) {
	return Boolean(config && /^[0-9a-f-]{36}$/i.test(owner || "") && (config.mode === "live" || config.allowedUsers.has(owner)));
}
function assertBillingOwner(config, owner) {
	if (!billingOwnerEnabled(config, owner)) throw new BillingError(403, "Billing is restricted to authorized accounts.");
}
var idOf = (value) => typeof value === "string" ? value : value?.id;
function safeStripeUrl(raw, host) {
	let url;
	try {
		url = new URL(raw);
	} catch {
		throw new BillingError(503, "Stripe did not return a valid link.");
	}
	if (url.protocol !== "https:" || url.hostname !== host || url.username || url.password) throw new BillingError(503, "Stripe did not return a valid link.");
	return url.href;
}
function createBillingService({ config, stripe, store, now = Date.now }) {
	const providerObject = (object) => {
		if (!object || object.livemode !== (config.mode === "live")) throw new BillingError(503, `Stripe ${config.mode} could not be verified.`);
		return object;
	};
	const back = `${config.origin}/?billing=returned#dashboard`;
	async function verifyAccount() {
		const account = await stripe.accounts.retrieve();
		if (account.id !== config.accountId) throw new BillingError(503, "Stripe account does not match billing configuration.");
		if (config.mode === "live" && account.charges_enabled !== true) throw new BillingError(503, "Stripe payments are not enabled.");
	}
	async function subscriptions(customer) {
		const all = [];
		let cursor;
		do {
			const page = await stripe.subscriptions.list({
				customer,
				status: "all",
				limit: 100,
				...cursor ? { starting_after: cursor } : {}
			});
			for (const sub of page.data) {
				providerObject(sub);
				if (idOf(sub.customer) !== customer) throw new BillingError(503, "Subscription ownership could not be verified.");
				all.push(sub);
			}
			cursor = page.has_more ? page.data.at(-1)?.id : null;
			if (page.has_more && (!cursor || all.length >= 1e3)) throw new BillingError(503, "Subscription history needs review.");
		} while (cursor);
		return all;
	}
	async function ensureCustomer(row, save, user) {
		if (!row.customerId) {
			row.customerAttempt ||= {
				id: randomUUID(),
				started: now()
			};
			await save();
			if (now() - row.customerAttempt.started > 1380 * 60 * 1e3) throw new BillingError(409, "An earlier billing setup needs review. Contact support.");
			row.customerId = providerObject(await stripe.customers.create({
				email: user.email,
				metadata: {
					cova_user_id: user.id,
					cova_environment: config.mode
				}
			}, { idempotencyKey: `cova:${row.customerAttempt.id}` })).id;
			await save();
		}
		const customer = providerObject(await stripe.customers.retrieve(row.customerId));
		if (customer.deleted || customer.metadata?.cova_user_id !== user.id) throw new BillingError(409, "Billing ownership could not be verified.");
	}
	const matchingSubscriptions = (all) => all.filter((s) => s.items?.data?.length === 1 && idOf(s.items.data[0].price) === config.priceId && s.items.data[0].quantity === 1);
	const cancellableSubscriptions = (all) => matchingSubscriptions(all).filter((s) => [
		"active",
		"trialing",
		"past_due",
		"unpaid"
	].includes(s.status) && !s.schedule);
	const scheduled = (sub) => Boolean(sub.cancel_at_period_end) || sub.cancel_at != null;
	const response = (state, user) => ({
		...state,
		plan: user.plan === "pro" ? "pro" : state.plan,
		accessSource: user.plan === "pro" ? "included" : state.plan === "pro" ? "subscription" : "free",
		ownerId: user.id,
		mode: config.mode,
		amount: config.amount,
		currency: "usd",
		interval: "month"
	});
	const invoiceLine = (invoice, sub) => invoice.lines?.data?.find((l) => l.quantity === 1 && idOf(l.pricing?.price_details?.price || l.price) === config.priceId && idOf(l.parent?.subscription_item_details?.subscription || l.subscription) === sub.id);
	const paymentStatuses = /* @__PURE__ */ new Set([
		"active",
		"incomplete",
		"past_due",
		"unpaid"
	]);
	const unpaidInvoice = (invoice, sub, customer) => invoice.id === idOf(sub.latest_invoice) && invoice.status === "open" && idOf(invoice.customer) === customer && invoice.currency === "usd" && Number.isSafeInteger(invoice.amount_remaining) && invoice.amount_remaining > 0 && !invoice.lines?.has_more && Boolean(invoiceLine(invoice, sub)) && typeof invoice.hosted_invoice_url === "string";
	async function reconcile(row, save) {
		let unpaid = 0;
		const state = {
			plan: "free",
			status: "none",
			paidUntil: null,
			cancelAtPeriodEnd: false,
			hasSubscription: false,
			canCancel: false,
			canManage: Boolean(row.customerId),
			canCheckout: true,
			paymentRequired: false,
			canRecoverPayment: false
		};
		if (row.customerId) {
			const customer = providerObject(await stripe.customers.retrieve(row.customerId));
			if (customer.deleted || customer.metadata?.cova_user_id !== row.ownerId) throw new BillingError(409, "Billing ownership could not be verified.");
			const all = await subscriptions(row.customerId);
			state.canCheckout = !all.some((s) => !["canceled", "incomplete_expired"].includes(s.status));
			const matching = matchingSubscriptions(all);
			state.hasSubscription = matching.some((s) => !["canceled", "incomplete_expired"].includes(s.status));
			const cancellable = cancellableSubscriptions(all);
			state.canCancel = cancellable.length === 1 && !scheduled(cancellable[0]);
			state.cancelAtPeriodEnd = cancellable.length === 1 && scheduled(cancellable[0]);
			matching.sort((a, b) => (b.created || 0) - (a.created || 0));
			state.status = matching[0]?.status || "none";
			for (const sub of matching) {
				if (!paymentStatuses.has(sub.status) || !idOf(sub.latest_invoice)) continue;
				const invoice = providerObject(await stripe.invoices.retrieve(idOf(sub.latest_invoice)));
				if (unpaidInvoice(invoice, sub, row.customerId)) {
					state.paymentRequired = true;
					unpaid++;
				}
				if (sub.status !== "active" || invoice.status !== "paid" || idOf(invoice.customer) !== row.customerId) continue;
				if (invoice.lines?.has_more) throw new BillingError(503, "Invoice details need review.");
				const line = invoiceLine(invoice, sub);
				const paidEnd = Number(line?.period?.end) * 1e3;
				const cancelAt = sub.cancel_at == null ? null : Number(sub.cancel_at) * 1e3;
				if (cancelAt !== null && (!Number.isSafeInteger(cancelAt) || cancelAt <= 0)) throw new BillingError(503, "Subscription cancellation needs review.");
				const until = cancelAt === null ? paidEnd : Math.min(paidEnd, cancelAt);
				if (!Number.isSafeInteger(until) || until <= now()) continue;
				if (!state.paidUntil || until > Date.parse(state.paidUntil)) Object.assign(state, {
					plan: "pro",
					status: "active",
					paidUntil: new Date(until).toISOString(),
					cancelAtPeriodEnd: Boolean(sub.cancel_at_period_end) || cancelAt !== null
				});
			}
		}
		state.canRecoverPayment = unpaid === 1;
		row.state = state;
		row.verifiedAt = now();
		await save();
		return state;
	}
	return {
		async status(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				const state = await reconcile(row, save);
				return response(state, user);
			});
		},
		async cancel(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No paid subscription to cancel.");
				await reconcile(row, save);
				const candidates = cancellableSubscriptions(await subscriptions(row.customerId));
				if (candidates.length !== 1) throw new BillingError(409, candidates.length ? "Use Manage billing to review your subscriptions." : "No eligible subscription to cancel.");
				const sub = candidates[0];
				if (!scheduled(sub)) {
					const updated = providerObject(await stripe.subscriptions.update(sub.id, { cancel_at_period_end: true }));
					if (updated.id !== sub.id || idOf(updated.customer) !== row.customerId || !scheduled(updated)) throw new BillingError(503, "Cancellation could not be verified. Refresh billing.");
				}
				const state = await reconcile(row, save);
				if (!state.cancelAtPeriodEnd) throw new BillingError(503, "Cancellation could not be verified. Refresh billing.");
				return response(state, user);
			});
		},
		async recover(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No billing account exists yet.");
				await reconcile(row, save);
				const pending = [];
				for (const sub of matchingSubscriptions(await subscriptions(row.customerId))) {
					if (!paymentStatuses.has(sub.status) || !idOf(sub.latest_invoice)) continue;
					const invoice = providerObject(await stripe.invoices.retrieve(idOf(sub.latest_invoice)));
					if (unpaidInvoice(invoice, sub, row.customerId)) pending.push({
						invoice,
						sub
					});
				}
				if (pending.length !== 1) throw new BillingError(409, pending.length ? "Use Manage billing to review your invoices." : "No unpaid subscription invoice to recover. Refresh billing.");
				const { invoice, sub } = pending[0];
				const url = safeStripeUrl(invoice.hosted_invoice_url, "invoice.stripe.com");
				if (sub.payment_settings?.save_default_payment_method !== "on_subscription") {
					const subscriptionId = sub.id;
					const updated = providerObject(await stripe.subscriptions.update(subscriptionId, { payment_settings: { save_default_payment_method: "on_subscription" } }));
					if (updated.id !== subscriptionId || idOf(updated.customer) !== row.customerId || matchingSubscriptions([updated]).length !== 1 || idOf(updated.latest_invoice) !== invoice.id || updated.payment_settings?.save_default_payment_method !== "on_subscription") throw new BillingError(503, "Payment recovery could not be prepared. Refresh billing.");
				}
				return { url };
			});
		},
		async portal(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No billing account exists yet.");
				await reconcile(row, save);
				return { url: safeStripeUrl((await stripe.billingPortal.sessions.create({
					customer: row.customerId,
					configuration: config.portalId,
					return_url: back
				})).url, "billing.stripe.com") };
			});
		},
		async assertDeletable(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (row.customerId || row.customerAttempt) throw new BillingError(409, "Close billing with support before deleting this account.");
				row.deleting = true;
				await save();
			});
		},
		async webhook(event) {
			providerObject(event);
			if (event.account && event.account !== config.accountId) throw new BillingError(400, "Wrong Stripe account.");
			if (!/^(customer\.subscription\.(created|updated|deleted)|invoice\.(paid|payment_failed|payment_action_required)|checkout\.session\.(completed|async_payment_succeeded|async_payment_failed))$/.test(event.type || "")) return { received: true };
			await verifyAccount();
			const customer = idOf(event.data?.object?.customer);
			if (!customer) return { received: true };
			const owner = await store.ownerForCustomer(customer);
			if (!owner) return { received: true };
			assertBillingOwner(config, owner);
			return store.withOwner(owner, async (row, save) => {
				if (row.customerId !== customer) throw new BillingError(409, "Billing ownership could not be verified.");
				if (row.events?.includes(event.id)) return { received: true };
				const pendingSave = async () => {};
				await reconcile(row, pendingSave);
				row.events = [...(row.events || []).slice(-255), event.id];
				await save();
				return { received: true };
			});
		},
		async checkout(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (row.deleting) throw new BillingError(409, "Account deletion is in progress.");
				await ensureCustomer(row, save, user);
				const existing = await subscriptions(row.customerId);
				if (existing.some((s) => !["canceled", "incomplete_expired"].includes(s.status))) throw new BillingError(409, "A subscription already exists. Use Manage billing.");
				if (row.checkoutAttempt?.sessionId) {
					const previous = providerObject(await stripe.checkout.sessions.retrieve(row.checkoutAttempt.sessionId));
					if (idOf(previous.customer) !== row.customerId) throw new BillingError(409, "Checkout ownership could not be verified.");
					if (previous.status === "open") return { url: safeStripeUrl(previous.url, "checkout.stripe.com") };
					if (previous.status === "complete") {
						const linked = existing.find((s) => s.id === idOf(previous.subscription));
						if (!linked || !["canceled", "incomplete_expired"].includes(linked.status)) throw new BillingError(409, "Your checkout is being confirmed. Refresh billing.");
					} else if (previous.status !== "expired") throw new BillingError(409, "The previous checkout needs review.");
					row.checkoutAttempt = null;
					await save();
				}
				const price = providerObject(await stripe.prices.retrieve(config.priceId));
				if (!price.active || price.unit_amount !== config.amount || price.currency !== "usd" || price.recurring?.interval !== "month" || price.recurring?.interval_count !== 1) throw new BillingError(503, "The monthly price could not be verified.");
				row.checkoutAttempt ||= {
					id: randomUUID(),
					started: now()
				};
				await save();
				if (now() - row.checkoutAttempt.started > 1380 * 60 * 1e3) throw new BillingError(409, "An earlier checkout needs review. Contact support.");
				const session = providerObject(await stripe.checkout.sessions.create({
					mode: "subscription",
					ui_mode: "hosted_page",
					branding_settings: {
						background_color: "#0B1017",
						button_color: "#315DCA",
						border_style: "rounded",
						font_family: "default",
						display_name: "Cova",
						logo: {
							type: "url",
							url: "https://covadesk.com/media/wordmark-options/cova-wordmark-option-3-sleek-cropped.png"
						}
					},
					managed_payments: { enabled: false },
					customer: row.customerId,
					client_reference_id: user.id,
					line_items: [{
						price: config.priceId,
						quantity: 1
					}],
					subscription_data: { metadata: {
						cova_user_id: user.id,
						cova_environment: config.mode
					} },
					success_url: back,
					cancel_url: `${config.origin}/?billing=canceled#dashboard`,
					allow_promotion_codes: false,
					automatic_tax: { enabled: false },
					payment_method_types: ["card"],
					phone_number_collection: { enabled: false }
				}, { idempotencyKey: `cova:${row.checkoutAttempt.id}` }));
				row.checkoutAttempt.sessionId = session.id;
				await save();
				return { url: safeStripeUrl(session.url, "checkout.stripe.com") };
			});
		}
	};
}
//#endregion
//#region api/_lib/billing-store.js
function createBillingStore(config, { env = process.env, fetchImpl = fetch, command: override } = {}) {
	const prefix = `cova:billing:v1:${config.mode || "sandbox"}:${config.accountId}:`;
	async function command(args) {
		if (override) return override(args);
		const url = new URL(env.KV_REST_API_URL || "https://unconfigured.invalid");
		if (url.protocol !== "https:" || !url.hostname.endsWith(".upstash.io") || url.username || url.password || !env.KV_REST_API_TOKEN) throw new BillingError(503, "Billing storage is not configured.");
		const response = await fetchImpl(url, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${env.KV_REST_API_TOKEN}`,
				"Content-Type": "application/json"
			},
			body: JSON.stringify(args),
			signal: AbortSignal.timeout(5e3)
		});
		if (!response.ok) throw new BillingError(503, "Billing storage is unavailable.");
		const result = await response.json();
		if (result.error || !Object.hasOwn(result, "result")) throw new BillingError(503, "Billing storage rejected the update.");
		return result.result;
	}
	const ownerKey = (owner) => `${prefix}owner:${owner}`;
	return {
		async read(owner) {
			const raw = await command(["GET", ownerKey(owner)]);
			return raw ? JSON.parse(raw) : null;
		},
		async ownerForCustomer(customer) {
			return command(["GET", `${prefix}customer:${customer}`]);
		},
		async withOwner(owner, run) {
			const key = ownerKey(owner), lock = key + ":lock", token = randomUUID();
			const attemptKey = key + ":attempts";
			const attempts = await command(["INCR", attemptKey]);
			if (attempts === 1) await command([
				"EXPIRE",
				attemptKey,
				60
			]);
			if (attempts > 60) throw new BillingError(429, "Billing is busy. Try again in a minute.");
			if (await command([
				"SET",
				lock,
				token,
				"NX",
				"EX",
				120
			]) !== "OK") throw new BillingError(409, "Billing is updating. Try again in a moment.");
			try {
				const raw = await command(["GET", key]);
				const row = raw ? JSON.parse(raw) : { ownerId: owner };
				if (row.ownerId !== owner) throw new BillingError(409, "Billing ownership mismatch.");
				const originalCustomer = row.customerId;
				const save = async () => {
					if (row.ownerId !== owner || originalCustomer && row.customerId !== originalCustomer) throw new BillingError(409, "Billing ownership mismatch.");
					const mapping = row.customerId ? `${prefix}customer:${row.customerId}` : key;
					const code = await command([
						"EVAL",
						"if redis.call('GET',KEYS[1])~=ARGV[1] then return 0 end; if KEYS[3]~=KEYS[2] then local owner=redis.call('GET',KEYS[3]); if owner and owner~=ARGV[3] then return -1 end; redis.call('SET',KEYS[3],ARGV[3]); end; redis.call('SET',KEYS[2],ARGV[2]); return 1",
						3,
						lock,
						key,
						mapping,
						token,
						JSON.stringify(row),
						owner
					]);
					if (code !== 1) throw new BillingError(409, code === -1 ? "Billing customer ownership mismatch." : "Billing update expired. Retry to verify current state.");
				};
				return await run(row, save);
			} finally {
				await command([
					"EVAL",
					"if redis.call('GET',KEYS[1])==ARGV[1] then return redis.call('DEL',KEYS[1]) else return 0 end",
					1,
					lock,
					token
				]).catch(() => {});
			}
		}
	};
}
//#endregion
//#region api/_lib/billing-runtime.js
function billingRuntime(options = {}) {
	const config = billingConfig(options.env || process.env);
	if (!config) return null;
	const stripe = stripeClient(config), store = createBillingStore(config, options);
	return {
		config,
		stripe,
		store,
		service: createBillingService({
			config,
			stripe,
			store
		})
	};
}
async function resolveBillingPlan(user, options = {}) {
	const env = options.env || process.env;
	if (user.plan === "pro" || !env.COVA_BILLING_MODE) return user.plan;
	const runtime = billingRuntime(options);
	if (!billingOwnerEnabled(runtime?.config, user.id)) return user.plan;
	const cached = await runtime.store.read(user.id);
	if (cached && cached.ownerId !== user.id) throw new BillingError(409, "Billing ownership mismatch.");
	if (!cached?.customerId) return user.plan;
	if (cached?.state && Date.now() - cached.verifiedAt >= 0 && Date.now() - cached.verifiedAt < 6e4) return cached.state.plan === "pro" && Date.parse(cached.state.paidUntil) > Date.now() ? "pro" : "free";
	return (await runtime.service.status(user)).plan;
}
//#endregion
//#region api/_lib/supabase.js
function getSupabaseConfig() {
	const supabaseUrl = process.env.SUPABASE_URL;
	const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
	if (!supabaseUrl || !serviceRoleKey) throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
	return {
		supabaseUrl: supabaseUrl.replace(/\/$/, ""),
		serviceRoleKey
	};
}
function supabaseServiceHeaders(serviceRoleKey, extra = {}) {
	const headers = {
		apikey: serviceRoleKey,
		"Content-Type": "application/json"
	};
	if (!serviceRoleKey.startsWith("sb_secret_")) headers.Authorization = ["Bearer", serviceRoleKey].join(" ");
	return {
		...headers,
		...extra
	};
}
async function requireSuccess(response, message) {
	if (!response.ok) throw new Error(`${message} (${response.status}).`);
	return response;
}
function connectionExpiryIsInvalid(connection, provider) {
	if (!connection) return false;
	if (!connection.expires_at) return provider === "tradovate";
	const expiry = Date.parse(String(connection.expires_at));
	return !Number.isFinite(expiry) || expiry <= Date.now();
}
async function getTradovateLinkForUser(userId) {
	if (!userId) return null;
	const { supabaseUrl, serviceRoleKey } = getSupabaseConfig();
	const endpoint = new URL(`${supabaseUrl}/rest/v1/broker_connections`);
	endpoint.searchParams.set("user_id", `eq.${userId}`);
	endpoint.searchParams.set("provider", "eq.tradovate");
	endpoint.searchParams.set("status", "in.(connected,expired)");
	endpoint.searchParams.set("select", "id,status,expires_at");
	endpoint.searchParams.set("order", "created_at.desc");
	endpoint.searchParams.set("limit", "1");
	const response = await fetch(endpoint, { headers: supabaseServiceHeaders(serviceRoleKey) });
	await requireSuccess(response, "Secure storage rejected the owner link lookup");
	return (await response.json())?.[0] || null;
}
async function listBrokerConnectionsForUser(userId) {
	const { supabaseUrl, serviceRoleKey } = getSupabaseConfig();
	const endpoint = new URL(`${supabaseUrl}/rest/v1/broker_connections`);
	endpoint.searchParams.set("user_id", `eq.${userId}`);
	endpoint.searchParams.set("select", "provider,status,expires_at");
	endpoint.searchParams.set("order", "created_at.desc");
	const response = await fetch(endpoint, { headers: supabaseServiceHeaders(serviceRoleKey) });
	await requireSuccess(response, "Stored connector status lookup");
	const rows = await response.json();
	return Array.isArray(rows) ? rows : [];
}
async function deleteBrokerConnectionsForUser(userId) {
	if (!userId) return false;
	const { supabaseUrl, serviceRoleKey } = getSupabaseConfig();
	const endpoint = new URL(`${supabaseUrl}/rest/v1/broker_connections`);
	endpoint.searchParams.set("user_id", `eq.${userId}`);
	await requireSuccess(await fetch(endpoint, {
		method: "DELETE",
		headers: supabaseServiceHeaders(serviceRoleKey, { Prefer: "return=minimal" })
	}), "Secure storage rejected account connection deletion");
	return true;
}
async function deleteBrokerConnectionsForProvider({ provider, userId }) {
	if (!provider || !userId) return false;
	const { supabaseUrl, serviceRoleKey } = getSupabaseConfig();
	const endpoint = new URL(`${supabaseUrl}/rest/v1/broker_connections`);
	endpoint.searchParams.set("user_id", `eq.${userId}`);
	endpoint.searchParams.set("provider", `eq.${provider}`);
	await requireSuccess(await fetch(endpoint, {
		method: "DELETE",
		headers: supabaseServiceHeaders(serviceRoleKey, { Prefer: "return=minimal" })
	}), "Secure storage rejected provider connection deletion");
	return true;
}
//#endregion
//#region api/_lib/auth.js
var ApiError = class extends Error {
	constructor(statusCode, message) {
		super(message);
		this.name = "ApiError";
		this.statusCode = statusCode;
	}
};
function getBearerToken(req) {
	return String(req.headers?.authorization || "").match(/^Bearer\s+(.+)$/i)?.[1]?.trim() || "";
}
async function requireAuthenticatedUser(req, { fetchImpl = fetch, timeoutMs = 5e3, billing = true } = {}) {
	const token = getBearerToken(req);
	if (!token) throw new ApiError(401, "Sign in to continue.");
	const supabaseUrl = String(process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "").replace(/\/$/, "");
	const apiKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || "";
	if (!supabaseUrl || !apiKey) throw new ApiError(503, "Member authentication is not configured.");
	let response;
	try {
		response = await fetchImpl(`${supabaseUrl}/auth/v1/user`, {
			headers: {
				apikey: apiKey,
				Authorization: `Bearer ${token}`
			},
			signal: AbortSignal.timeout(timeoutMs)
		});
	} catch {
		throw new ApiError(503, "Member authentication is temporarily unavailable.");
	}
	if (!response.ok) throw new ApiError(401, "Your Cova session is invalid or expired. Sign in again.");
	const user = await response.json();
	if (!user?.id) throw new ApiError(401, "Your Cova session could not be verified.");
	return {
		id: String(user.id),
		email: typeof user.email === "string" ? user.email : "",
		plan: billing ? await resolveBillingPlan({
			id: String(user.id),
			plan: user.app_metadata?.plan === "pro" ? "pro" : "free"
		}, { fetchImpl }) : user.app_metadata?.plan === "pro" ? "pro" : "free"
	};
}
function sendApiError(res, error, fallbackMessage) {
	const statusCode = Number.isInteger(error?.statusCode) ? error.statusCode : 500;
	const message = statusCode >= 500 ? fallbackMessage : error?.message || fallbackMessage;
	return res.status(statusCode).json({ error: message });
}
//#endregion
//#region api/_lib/cookies.js
function parseCookies(req) {
	return (req.headers?.cookie || "").split(";").reduce((cookies, pair) => {
		const [name, ...valueParts] = pair.trim().split("=");
		if (!name) return cookies;
		cookies[name] = decodeURIComponent(valueParts.join("=") || "");
		return cookies;
	}, {});
}
function serializeCookie(name, value, options = {}) {
	const parts = [`${name}=${encodeURIComponent(value)}`];
	parts.push(`Path=${options.path || "/"}`);
	if (options.maxAge !== void 0) parts.push(`Max-Age=${options.maxAge}`);
	if (options.httpOnly !== false) parts.push("HttpOnly");
	parts.push(`SameSite=${options.sameSite || "Lax"}`);
	if (options.secure ?? process.env.NODE_ENV === "production") parts.push("Secure");
	return parts.join("; ");
}
function clearCookie(name) {
	return serializeCookie(name, "", { maxAge: 0 });
}
//#endregion
//#region api/_lib/tradovate-capability.js
var REQUIRED_TRADOVATE_ENV = [
	"COVA_TOKEN_ENCRYPTION_KEY",
	"KV_REST_API_TOKEN",
	"KV_REST_API_URL",
	"SUPABASE_SERVICE_ROLE_KEY",
	"SUPABASE_URL",
	"TRADOVATE_CLIENT_ID",
	"TRADOVATE_CLIENT_SECRET"
];
function tradovateEnvironmentReady(env = process.env) {
	return REQUIRED_TRADOVATE_ENV.every((name) => String(env?.[name] || "").trim().length > 0);
}
//#endregion
//#region server/connectors/status.js
function requestedProvider(req) {
	const value = Array.isArray(req.query?.provider) ? req.query.provider[0] : req.query?.provider;
	return typeof value === "string" ? value.trim().toLowerCase() : "";
}
async function sendTradovateStatus(req, res, userId) {
	const connectionId = parseCookies(req).cova_tradovate_connection || "";
	const available = tradovateEnvironmentReady();
	const connection = await getTradovateLinkForUser(userId);
	if (!connection) {
		if (connectionId) res.setHeader("Set-Cookie", clearCookie("cova_tradovate_connection"));
		return res.status(200).json({
			available,
			connected: false,
			linked: false,
			provider: "Tradovate",
			status: available ? "not-connected" : "unavailable"
		});
	}
	if (connection.id && connection.id !== connectionId) res.setHeader("Set-Cookie", serializeCookie("cova_tradovate_connection", connection.id, { maxAge: 3600 * 24 * 30 }));
	const reconnectRequired = connection.status !== "connected" || connectionExpiryIsInvalid(connection, "tradovate");
	return res.status(200).json({
		available,
		connected: !reconnectRequired,
		linked: true,
		connectionId: connection.id,
		provider: "Tradovate",
		status: reconnectRequired ? "reconnect-required" : available ? "connected" : "configuration-unavailable",
		expiresAt: connection.expires_at
	});
}
async function handler$2(req, res) {
	if (req.method !== "GET") {
		res.setHeader("Allow", "GET");
		return res.status(405).json({ error: "Method not allowed" });
	}
	const provider = requestedProvider(req);
	try {
		const user = await requireAuthenticatedUser(req);
		res.setHeader("Cache-Control", "private, no-store");
		if (provider === "tradovate") return await sendTradovateStatus(req, res, user.id);
		if (provider) return res.status(400).json({ error: "Unsupported provider" });
		const rows = await listBrokerConnectionsForUser(user.id);
		return res.status(200).json({ providers: rows.map((row) => ({
			expiresAt: typeof row.expires_at === "string" ? row.expires_at : null,
			provider: String(row.provider || "unknown"),
			status: row.provider === "tradovate" && (row.status === "expired" || row.status === "connected" && connectionExpiryIsInvalid(row, "tradovate")) ? "reconnect-required" : String(row.status || "connected")
		})) });
	} catch (error) {
		return sendApiError(res, error, provider === "tradovate" ? "Tradovate status is unavailable." : "Saved provider status is unavailable.");
	}
}
//#endregion
//#region server/connectors/disconnect.js
var providers = {
	projectx: {
		cookie: "cova_projectx_connection",
		label: "TopstepX"
	},
	tradovate: {
		cookie: "cova_tradovate_connection",
		label: "Tradovate"
	}
};
async function handler$1(req, res) {
	if (req.method !== "POST") {
		res.setHeader("Allow", "POST");
		return res.status(405).json({ error: "Method not allowed" });
	}
	try {
		const user = await requireAuthenticatedUser(req);
		const body = typeof req.body === "string" ? JSON.parse(req.body || "{}") : req.body || {};
		const provider = String(body.provider || "").toLowerCase();
		const config = providers[provider];
		if (provider !== "all" && !config) return res.status(400).json({ error: "Choose a supported connection to disconnect." });
		if (provider === "all") {
			await deleteBrokerConnectionsForUser(user.id);
			res.setHeader("Cache-Control", "private, no-store");
			res.setHeader("Set-Cookie", [
				clearCookie(providers.projectx.cookie),
				clearCookie(providers.tradovate.cookie),
				clearCookie("cova_oauth_context")
			]);
			return res.status(200).json({
				disconnected: true,
				provider: "All Cova connectors"
			});
		}
		await deleteBrokerConnectionsForProvider({
			provider,
			userId: user.id
		});
		res.setHeader("Cache-Control", "no-store");
		res.setHeader("Set-Cookie", [clearCookie(config.cookie), clearCookie("cova_oauth_context")]);
		return res.status(200).json({
			disconnected: true,
			provider: config.label
		});
	} catch (error) {
		return sendApiError(res, error, "The connection could not be removed securely.");
	}
}
//#endregion
//#region scripts/test-connectors-entry.mjs
function handler(req, res) {
	const path = new URL(req.url || "/", "https://local.invalid").pathname;
	if (path === "/api/connectors/status" || path === "/api/tradovate/status") return handler$2(req, res);
	if (path === "/api/connectors/disconnect") return handler$1(req, res);
	return res.status(404).json({ error: "Not found" });
}
//#endregion
export { handler as default };
