// Generated by scripts/build-server-runtimes.mjs from server/workspace.ts. Do not edit this artifact.
import { createHash, randomUUID } from "node:crypto";
import Stripe from "stripe";
//#region api/_lib/billing.js
var BillingError = class extends Error {
	constructor(statusCode, message) {
		super(message);
		this.statusCode = statusCode;
	}
};
function billingConfig(env = process.env) {
	if (!env.COVA_BILLING_MODE) return null;
	const mode = env.COVA_BILLING_MODE, live = mode === "live";
	if (live) {
		if (env.COVA_BILLING_LIVE_ENABLED !== "true" || env.VERCEL_ENV !== "production" || env.VERCEL_TARGET_ENV && env.VERCEL_TARGET_ENV !== "production") throw new BillingError(503, "Live billing is disabled in this environment.");
		if (!/^(sk|rk)_live_/.test(env.STRIPE_SECRET_KEY || "")) throw new BillingError(503, "A live Stripe key is required.");
		if (!/^whsec_/.test(env.STRIPE_WEBHOOK_SECRET || "")) throw new BillingError(503, "Live billing webhook is not configured.");
	} else {
		if (mode !== "sandbox" || env.VERCEL_ENV === "production" || env.VERCEL_TARGET_ENV === "production") throw new BillingError(503, "Billing is disabled in this environment.");
		if (!/^(sk|rk)_test_/.test(env.STRIPE_SECRET_KEY || "")) throw new BillingError(503, "A sandbox Stripe key is required.");
	}
	const allowedUsers = new Set(String(env.COVA_BILLING_ALLOWED_USERS || "").split(",").map((v) => v.trim()).filter((v) => /^[0-9a-f-]{36}$/i.test(v)));
	if (!live && !allowedUsers.size) throw new BillingError(503, "A sandbox owner allowlist is required.");
	let origin;
	try {
		origin = new URL(env.COVA_BILLING_ORIGIN);
	} catch {
		throw new BillingError(503, "Billing origin is not configured.");
	}
	if (origin.protocol !== "https:" || origin.username || origin.password || origin.pathname !== "/" || origin.search || origin.hash || (live ? origin.origin !== "https://covadesk.com" : ["covadesk.com", "www.covadesk.com"].includes(origin.hostname))) throw new BillingError(503, live ? "Use the canonical live billing origin." : "Use an isolated HTTPS billing preview.");
	if (!/^acct_[a-zA-Z0-9]+$/.test(env.STRIPE_ACCOUNT_ID || "") || !/^price_[a-zA-Z0-9]+$/.test(env.STRIPE_PRO_PRICE_ID || "") || !/^bpc_[a-zA-Z0-9]+$/.test(env.STRIPE_PORTAL_CONFIGURATION_ID || "")) throw new BillingError(503, "Billing is not configured.");
	return {
		mode,
		amount: live ? 2900 : 3e3,
		allowedUsers,
		origin: origin.origin,
		accountId: env.STRIPE_ACCOUNT_ID,
		priceId: env.STRIPE_PRO_PRICE_ID,
		portalId: env.STRIPE_PORTAL_CONFIGURATION_ID,
		key: env.STRIPE_SECRET_KEY,
		webhookSecret: env.STRIPE_WEBHOOK_SECRET || ""
	};
}
function stripeClient(config) {
	return new Stripe(config.key, {
		apiVersion: "2026-08-26.dahlia",
		maxNetworkRetries: 1,
		timeout: 1e4
	});
}
function billingOwnerEnabled(config, owner) {
	return Boolean(config && /^[0-9a-f-]{36}$/i.test(owner || "") && (config.mode === "live" || config.allowedUsers.has(owner)));
}
function assertBillingOwner(config, owner) {
	if (!billingOwnerEnabled(config, owner)) throw new BillingError(403, "Billing is restricted to authorized accounts.");
}
var idOf = (value) => typeof value === "string" ? value : value?.id;
function safeStripeUrl(raw, host) {
	let url;
	try {
		url = new URL(raw);
	} catch {
		throw new BillingError(503, "Stripe did not return a valid link.");
	}
	if (url.protocol !== "https:" || url.hostname !== host || url.username || url.password) throw new BillingError(503, "Stripe did not return a valid link.");
	return url.href;
}
function createBillingService({ config, stripe, store, now = Date.now }) {
	const providerObject = (object) => {
		if (!object || object.livemode !== (config.mode === "live")) throw new BillingError(503, `Stripe ${config.mode} could not be verified.`);
		return object;
	};
	const back = `${config.origin}/?billing=returned#dashboard`;
	async function verifyAccount() {
		const account = await stripe.accounts.retrieve();
		if (account.id !== config.accountId) throw new BillingError(503, "Stripe account does not match billing configuration.");
		if (config.mode === "live" && account.charges_enabled !== true) throw new BillingError(503, "Stripe payments are not enabled.");
	}
	async function subscriptions(customer) {
		const all = [];
		let cursor;
		do {
			const page = await stripe.subscriptions.list({
				customer,
				status: "all",
				limit: 100,
				...cursor ? { starting_after: cursor } : {}
			});
			for (const sub of page.data) {
				providerObject(sub);
				if (idOf(sub.customer) !== customer) throw new BillingError(503, "Subscription ownership could not be verified.");
				all.push(sub);
			}
			cursor = page.has_more ? page.data.at(-1)?.id : null;
			if (page.has_more && (!cursor || all.length >= 1e3)) throw new BillingError(503, "Subscription history needs review.");
		} while (cursor);
		return all;
	}
	async function ensureCustomer(row, save, user) {
		if (!row.customerId) {
			row.customerAttempt ||= {
				id: randomUUID(),
				started: now()
			};
			await save();
			if (now() - row.customerAttempt.started > 1380 * 60 * 1e3) throw new BillingError(409, "An earlier billing setup needs review. Contact support.");
			row.customerId = providerObject(await stripe.customers.create({
				email: user.email,
				metadata: {
					cova_user_id: user.id,
					cova_environment: config.mode
				}
			}, { idempotencyKey: `cova:${row.customerAttempt.id}` })).id;
			await save();
		}
		const customer = providerObject(await stripe.customers.retrieve(row.customerId));
		if (customer.deleted || customer.metadata?.cova_user_id !== user.id) throw new BillingError(409, "Billing ownership could not be verified.");
	}
	const matchingSubscriptions = (all) => all.filter((s) => s.items?.data?.length === 1 && idOf(s.items.data[0].price) === config.priceId && s.items.data[0].quantity === 1);
	const cancellableSubscriptions = (all) => matchingSubscriptions(all).filter((s) => [
		"active",
		"trialing",
		"past_due",
		"unpaid"
	].includes(s.status) && !s.schedule);
	const scheduled = (sub) => Boolean(sub.cancel_at_period_end) || sub.cancel_at != null;
	const response = (state, user) => ({
		...state,
		plan: user.plan === "pro" ? "pro" : state.plan,
		accessSource: user.plan === "pro" ? "included" : state.plan === "pro" ? "subscription" : "free",
		ownerId: user.id,
		mode: config.mode,
		amount: config.amount,
		currency: "usd",
		interval: "month"
	});
	const invoiceLine = (invoice, sub) => invoice.lines?.data?.find((l) => l.quantity === 1 && idOf(l.pricing?.price_details?.price || l.price) === config.priceId && idOf(l.parent?.subscription_item_details?.subscription || l.subscription) === sub.id);
	const paymentStatuses = /* @__PURE__ */ new Set([
		"active",
		"incomplete",
		"past_due",
		"unpaid"
	]);
	const unpaidInvoice = (invoice, sub, customer) => invoice.id === idOf(sub.latest_invoice) && invoice.status === "open" && idOf(invoice.customer) === customer && invoice.currency === "usd" && Number.isSafeInteger(invoice.amount_remaining) && invoice.amount_remaining > 0 && !invoice.lines?.has_more && Boolean(invoiceLine(invoice, sub)) && typeof invoice.hosted_invoice_url === "string";
	async function reconcile(row, save) {
		let unpaid = 0;
		const state = {
			plan: "free",
			status: "none",
			paidUntil: null,
			cancelAtPeriodEnd: false,
			hasSubscription: false,
			canCancel: false,
			canManage: Boolean(row.customerId),
			canCheckout: true,
			paymentRequired: false,
			canRecoverPayment: false
		};
		if (row.customerId) {
			const customer = providerObject(await stripe.customers.retrieve(row.customerId));
			if (customer.deleted || customer.metadata?.cova_user_id !== row.ownerId) throw new BillingError(409, "Billing ownership could not be verified.");
			const all = await subscriptions(row.customerId);
			state.canCheckout = !all.some((s) => !["canceled", "incomplete_expired"].includes(s.status));
			const matching = matchingSubscriptions(all);
			state.hasSubscription = matching.some((s) => !["canceled", "incomplete_expired"].includes(s.status));
			const cancellable = cancellableSubscriptions(all);
			state.canCancel = cancellable.length === 1 && !scheduled(cancellable[0]);
			state.cancelAtPeriodEnd = cancellable.length === 1 && scheduled(cancellable[0]);
			matching.sort((a, b) => (b.created || 0) - (a.created || 0));
			state.status = matching[0]?.status || "none";
			for (const sub of matching) {
				if (!paymentStatuses.has(sub.status) || !idOf(sub.latest_invoice)) continue;
				const invoice = providerObject(await stripe.invoices.retrieve(idOf(sub.latest_invoice)));
				if (unpaidInvoice(invoice, sub, row.customerId)) {
					state.paymentRequired = true;
					unpaid++;
				}
				if (sub.status !== "active" || invoice.status !== "paid" || idOf(invoice.customer) !== row.customerId) continue;
				if (invoice.lines?.has_more) throw new BillingError(503, "Invoice details need review.");
				const line = invoiceLine(invoice, sub);
				const paidEnd = Number(line?.period?.end) * 1e3;
				const cancelAt = sub.cancel_at == null ? null : Number(sub.cancel_at) * 1e3;
				if (cancelAt !== null && (!Number.isSafeInteger(cancelAt) || cancelAt <= 0)) throw new BillingError(503, "Subscription cancellation needs review.");
				const until = cancelAt === null ? paidEnd : Math.min(paidEnd, cancelAt);
				if (!Number.isSafeInteger(until) || until <= now()) continue;
				if (!state.paidUntil || until > Date.parse(state.paidUntil)) Object.assign(state, {
					plan: "pro",
					status: "active",
					paidUntil: new Date(until).toISOString(),
					cancelAtPeriodEnd: Boolean(sub.cancel_at_period_end) || cancelAt !== null
				});
			}
		}
		state.canRecoverPayment = unpaid === 1;
		row.state = state;
		row.verifiedAt = now();
		await save();
		return state;
	}
	return {
		async status(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				const state = await reconcile(row, save);
				return response(state, user);
			});
		},
		async cancel(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No paid subscription to cancel.");
				await reconcile(row, save);
				const candidates = cancellableSubscriptions(await subscriptions(row.customerId));
				if (candidates.length !== 1) throw new BillingError(409, candidates.length ? "Use Manage billing to review your subscriptions." : "No eligible subscription to cancel.");
				const sub = candidates[0];
				if (!scheduled(sub)) {
					const updated = providerObject(await stripe.subscriptions.update(sub.id, { cancel_at_period_end: true }));
					if (updated.id !== sub.id || idOf(updated.customer) !== row.customerId || !scheduled(updated)) throw new BillingError(503, "Cancellation could not be verified. Refresh billing.");
				}
				const state = await reconcile(row, save);
				if (!state.cancelAtPeriodEnd) throw new BillingError(503, "Cancellation could not be verified. Refresh billing.");
				return response(state, user);
			});
		},
		async recover(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No billing account exists yet.");
				await reconcile(row, save);
				const pending = [];
				for (const sub of matchingSubscriptions(await subscriptions(row.customerId))) {
					if (!paymentStatuses.has(sub.status) || !idOf(sub.latest_invoice)) continue;
					const invoice = providerObject(await stripe.invoices.retrieve(idOf(sub.latest_invoice)));
					if (unpaidInvoice(invoice, sub, row.customerId)) pending.push({
						invoice,
						sub
					});
				}
				if (pending.length !== 1) throw new BillingError(409, pending.length ? "Use Manage billing to review your invoices." : "No unpaid subscription invoice to recover. Refresh billing.");
				const { invoice, sub } = pending[0];
				const url = safeStripeUrl(invoice.hosted_invoice_url, "invoice.stripe.com");
				if (sub.payment_settings?.save_default_payment_method !== "on_subscription") {
					const subscriptionId = sub.id;
					const updated = providerObject(await stripe.subscriptions.update(subscriptionId, { payment_settings: { save_default_payment_method: "on_subscription" } }));
					if (updated.id !== subscriptionId || idOf(updated.customer) !== row.customerId || matchingSubscriptions([updated]).length !== 1 || idOf(updated.latest_invoice) !== invoice.id || updated.payment_settings?.save_default_payment_method !== "on_subscription") throw new BillingError(503, "Payment recovery could not be prepared. Refresh billing.");
				}
				return { url };
			});
		},
		async portal(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (!row.customerId) throw new BillingError(409, "No billing account exists yet.");
				await reconcile(row, save);
				return { url: safeStripeUrl((await stripe.billingPortal.sessions.create({
					customer: row.customerId,
					configuration: config.portalId,
					return_url: back
				})).url, "billing.stripe.com") };
			});
		},
		async assertDeletable(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (row.customerId || row.customerAttempt) throw new BillingError(409, "Close billing with support before deleting this account.");
				row.deleting = true;
				await save();
			});
		},
		async webhook(event) {
			providerObject(event);
			if (event.account && event.account !== config.accountId) throw new BillingError(400, "Wrong Stripe account.");
			if (!/^(customer\.subscription\.(created|updated|deleted)|invoice\.(paid|payment_failed|payment_action_required)|checkout\.session\.(completed|async_payment_succeeded|async_payment_failed))$/.test(event.type || "")) return { received: true };
			await verifyAccount();
			const customer = idOf(event.data?.object?.customer);
			if (!customer) return { received: true };
			const owner = await store.ownerForCustomer(customer);
			if (!owner) return { received: true };
			assertBillingOwner(config, owner);
			return store.withOwner(owner, async (row, save) => {
				if (row.customerId !== customer) throw new BillingError(409, "Billing ownership could not be verified.");
				if (row.events?.includes(event.id)) return { received: true };
				const pendingSave = async () => {};
				await reconcile(row, pendingSave);
				row.events = [...(row.events || []).slice(-255), event.id];
				await save();
				return { received: true };
			});
		},
		async checkout(user) {
			assertBillingOwner(config, user.id);
			await verifyAccount();
			return store.withOwner(user.id, async (row, save) => {
				if (row.deleting) throw new BillingError(409, "Account deletion is in progress.");
				await ensureCustomer(row, save, user);
				const existing = await subscriptions(row.customerId);
				if (existing.some((s) => !["canceled", "incomplete_expired"].includes(s.status))) throw new BillingError(409, "A subscription already exists. Use Manage billing.");
				if (row.checkoutAttempt?.sessionId) {
					const previous = providerObject(await stripe.checkout.sessions.retrieve(row.checkoutAttempt.sessionId));
					if (idOf(previous.customer) !== row.customerId) throw new BillingError(409, "Checkout ownership could not be verified.");
					if (previous.status === "open") return { url: safeStripeUrl(previous.url, "checkout.stripe.com") };
					if (previous.status === "complete") {
						const linked = existing.find((s) => s.id === idOf(previous.subscription));
						if (!linked || !["canceled", "incomplete_expired"].includes(linked.status)) throw new BillingError(409, "Your checkout is being confirmed. Refresh billing.");
					} else if (previous.status !== "expired") throw new BillingError(409, "The previous checkout needs review.");
					row.checkoutAttempt = null;
					await save();
				}
				const price = providerObject(await stripe.prices.retrieve(config.priceId));
				if (!price.active || price.unit_amount !== config.amount || price.currency !== "usd" || price.recurring?.interval !== "month" || price.recurring?.interval_count !== 1) throw new BillingError(503, "The monthly price could not be verified.");
				row.checkoutAttempt ||= {
					id: randomUUID(),
					started: now()
				};
				await save();
				if (now() - row.checkoutAttempt.started > 1380 * 60 * 1e3) throw new BillingError(409, "An earlier checkout needs review. Contact support.");
				const session = providerObject(await stripe.checkout.sessions.create({
					mode: "subscription",
					ui_mode: "hosted_page",
					branding_settings: {
						background_color: "#0B1017",
						button_color: "#315DCA",
						border_style: "rounded",
						font_family: "default",
						display_name: "Cova",
						logo: {
							type: "url",
							url: "https://covadesk.com/media/wordmark-options/cova-wordmark-option-3-sleek-cropped.png"
						}
					},
					managed_payments: { enabled: false },
					customer: row.customerId,
					client_reference_id: user.id,
					line_items: [{
						price: config.priceId,
						quantity: 1
					}],
					subscription_data: { metadata: {
						cova_user_id: user.id,
						cova_environment: config.mode
					} },
					success_url: back,
					cancel_url: `${config.origin}/?billing=canceled#dashboard`,
					allow_promotion_codes: false,
					automatic_tax: { enabled: false },
					payment_method_types: ["card"],
					phone_number_collection: { enabled: false }
				}, { idempotencyKey: `cova:${row.checkoutAttempt.id}` }));
				row.checkoutAttempt.sessionId = session.id;
				await save();
				return { url: safeStripeUrl(session.url, "checkout.stripe.com") };
			});
		}
	};
}
//#endregion
//#region api/_lib/billing-store.js
function createBillingStore(config, { env = process.env, fetchImpl = fetch, command: override } = {}) {
	const prefix = `cova:billing:v1:${config.mode || "sandbox"}:${config.accountId}:`;
	async function command(args) {
		if (override) return override(args);
		const url = new URL(env.KV_REST_API_URL || "https://unconfigured.invalid");
		if (url.protocol !== "https:" || !url.hostname.endsWith(".upstash.io") || url.username || url.password || !env.KV_REST_API_TOKEN) throw new BillingError(503, "Billing storage is not configured.");
		const response = await fetchImpl(url, {
			method: "POST",
			headers: {
				Authorization: `Bearer ${env.KV_REST_API_TOKEN}`,
				"Content-Type": "application/json"
			},
			body: JSON.stringify(args),
			signal: AbortSignal.timeout(5e3)
		});
		if (!response.ok) throw new BillingError(503, "Billing storage is unavailable.");
		const result = await response.json();
		if (result.error || !Object.hasOwn(result, "result")) throw new BillingError(503, "Billing storage rejected the update.");
		return result.result;
	}
	const ownerKey = (owner) => `${prefix}owner:${owner}`;
	return {
		async read(owner) {
			const raw = await command(["GET", ownerKey(owner)]);
			return raw ? JSON.parse(raw) : null;
		},
		async ownerForCustomer(customer) {
			return command(["GET", `${prefix}customer:${customer}`]);
		},
		async withOwner(owner, run) {
			const key = ownerKey(owner), lock = key + ":lock", token = randomUUID();
			const attemptKey = key + ":attempts";
			const attempts = await command(["INCR", attemptKey]);
			if (attempts === 1) await command([
				"EXPIRE",
				attemptKey,
				60
			]);
			if (attempts > 60) throw new BillingError(429, "Billing is busy. Try again in a minute.");
			if (await command([
				"SET",
				lock,
				token,
				"NX",
				"EX",
				120
			]) !== "OK") throw new BillingError(409, "Billing is updating. Try again in a moment.");
			try {
				const raw = await command(["GET", key]);
				const row = raw ? JSON.parse(raw) : { ownerId: owner };
				if (row.ownerId !== owner) throw new BillingError(409, "Billing ownership mismatch.");
				const originalCustomer = row.customerId;
				const save = async () => {
					if (row.ownerId !== owner || originalCustomer && row.customerId !== originalCustomer) throw new BillingError(409, "Billing ownership mismatch.");
					const mapping = row.customerId ? `${prefix}customer:${row.customerId}` : key;
					const code = await command([
						"EVAL",
						"if redis.call('GET',KEYS[1])~=ARGV[1] then return 0 end; if KEYS[3]~=KEYS[2] then local owner=redis.call('GET',KEYS[3]); if owner and owner~=ARGV[3] then return -1 end; redis.call('SET',KEYS[3],ARGV[3]); end; redis.call('SET',KEYS[2],ARGV[2]); return 1",
						3,
						lock,
						key,
						mapping,
						token,
						JSON.stringify(row),
						owner
					]);
					if (code !== 1) throw new BillingError(409, code === -1 ? "Billing customer ownership mismatch." : "Billing update expired. Retry to verify current state.");
				};
				return await run(row, save);
			} finally {
				await command([
					"EVAL",
					"if redis.call('GET',KEYS[1])==ARGV[1] then return redis.call('DEL',KEYS[1]) else return 0 end",
					1,
					lock,
					token
				]).catch(() => {});
			}
		}
	};
}
//#endregion
//#region api/_lib/billing-runtime.js
function billingRuntime(options = {}) {
	const config = billingConfig(options.env || process.env);
	if (!config) return null;
	const stripe = stripeClient(config), store = createBillingStore(config, options);
	return {
		config,
		stripe,
		store,
		service: createBillingService({
			config,
			stripe,
			store
		})
	};
}
async function resolveBillingPlan(user, options = {}) {
	const env = options.env || process.env;
	if (user.plan === "pro" || !env.COVA_BILLING_MODE) return user.plan;
	const runtime = billingRuntime(options);
	if (!billingOwnerEnabled(runtime?.config, user.id)) return user.plan;
	const cached = await runtime.store.read(user.id);
	if (cached && cached.ownerId !== user.id) throw new BillingError(409, "Billing ownership mismatch.");
	if (!cached?.customerId) return user.plan;
	if (cached?.state && Date.now() - cached.verifiedAt >= 0 && Date.now() - cached.verifiedAt < 6e4) return cached.state.plan === "pro" && Date.parse(cached.state.paidUntil) > Date.now() ? "pro" : "free";
	return (await runtime.service.status(user)).plan;
}
//#endregion
//#region api/_lib/legal-policy.js
var CURRENT_TERMS_VERSION = "2026-07-22";
var CURRENT_PRIVACY_VERSION = "2026-07-22";
//#endregion
//#region api/_lib/supabase.js
function getSupabaseConfig() {
	const supabaseUrl = process.env.SUPABASE_URL;
	const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
	if (!supabaseUrl || !serviceRoleKey) throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
	return {
		supabaseUrl: supabaseUrl.replace(/\/$/, ""),
		serviceRoleKey
	};
}
function supabaseServiceHeaders(serviceRoleKey, extra = {}) {
	const headers = {
		apikey: serviceRoleKey,
		"Content-Type": "application/json"
	};
	if (!serviceRoleKey.startsWith("sb_secret_")) headers.Authorization = ["Bearer", serviceRoleKey].join(" ");
	return {
		...headers,
		...extra
	};
}
async function requireSuccess(response, message) {
	if (!response.ok) throw new Error(`${message} (${response.status}).`);
	return response;
}
async function hasPolicyAcceptance({ userId, termsVersion, privacyVersion }, { fetchImpl = fetch, timeoutMs = 5e3 } = {}) {
	if (!userId || !termsVersion || !privacyVersion) return false;
	const { supabaseUrl, serviceRoleKey } = getSupabaseConfig();
	const endpoint = new URL(`${supabaseUrl}/rest/v1/policy_acceptances`);
	endpoint.searchParams.set("user_id", `eq.${userId}`);
	endpoint.searchParams.set("terms_version", `eq.${termsVersion}`);
	endpoint.searchParams.set("privacy_version", `eq.${privacyVersion}`);
	endpoint.searchParams.set("select", "id");
	endpoint.searchParams.set("limit", "1");
	const response = await fetchImpl(endpoint, {
		headers: supabaseServiceHeaders(serviceRoleKey),
		signal: AbortSignal.timeout(timeoutMs)
	});
	await requireSuccess(response, "Secure storage rejected policy acceptance lookup");
	const rows = await response.json();
	return Array.isArray(rows) && rows.length === 1;
}
//#endregion
//#region api/_lib/auth.js
var ApiError = class extends Error {
	constructor(statusCode, message) {
		super(message);
		this.name = "ApiError";
		this.statusCode = statusCode;
	}
};
function getBearerToken(req) {
	return String(req.headers?.authorization || "").match(/^Bearer\s+(.+)$/i)?.[1]?.trim() || "";
}
async function requireAuthenticatedUser(req, { fetchImpl = fetch, timeoutMs = 5e3, billing = true } = {}) {
	const token = getBearerToken(req);
	if (!token) throw new ApiError(401, "Sign in to continue.");
	const supabaseUrl = String(process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL || "").replace(/\/$/, "");
	const apiKey = process.env.SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY || "";
	if (!supabaseUrl || !apiKey) throw new ApiError(503, "Member authentication is not configured.");
	let response;
	try {
		response = await fetchImpl(`${supabaseUrl}/auth/v1/user`, {
			headers: {
				apikey: apiKey,
				Authorization: `Bearer ${token}`
			},
			signal: AbortSignal.timeout(timeoutMs)
		});
	} catch {
		throw new ApiError(503, "Member authentication is temporarily unavailable.");
	}
	if (!response.ok) throw new ApiError(401, "Your Cova session is invalid or expired. Sign in again.");
	const user = await response.json();
	if (!user?.id) throw new ApiError(401, "Your Cova session could not be verified.");
	return {
		id: String(user.id),
		email: typeof user.email === "string" ? user.email : "",
		plan: billing ? await resolveBillingPlan({
			id: String(user.id),
			plan: user.app_metadata?.plan === "pro" ? "pro" : "free"
		}, { fetchImpl }) : user.app_metadata?.plan === "pro" ? "pro" : "free"
	};
}
async function requireCurrentPolicyAcceptance(userId, options = {}) {
	let accepted;
	try {
		accepted = await hasPolicyAcceptance({
			userId,
			termsVersion: CURRENT_TERMS_VERSION,
			privacyVersion: CURRENT_PRIVACY_VERSION
		}, options);
	} catch {
		throw new ApiError(503, "Cova could not verify policy acceptance.");
	}
	if (!accepted) throw new ApiError(403, "Accept the current Terms and Privacy Policy to continue.");
}
async function requirePolicyAcceptedUser(req, options = {}) {
	const user = await requireAuthenticatedUser(req, options);
	await requireCurrentPolicyAcceptance(user.id, options);
	return user;
}
function sendApiError(res, error, fallbackMessage) {
	const statusCode = Number.isInteger(error?.statusCode) ? error.statusCode : 500;
	const message = statusCode >= 500 ? fallbackMessage : error?.message || fallbackMessage;
	return res.status(statusCode).json({ error: message });
}
//#endregion
//#region src/lib/manualAccountKeys.ts
/** Identity only, never broker authorization or currency evidence. */
var isManualAccountKey = (key) => /^Manual:[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(key);
[
	[
		"2026-04-17",
		"NQ",
		"Long",
		2,
		18460.25,
		18483.75,
		940,
		500,
		"Opening range",
		"Waited for first pullback."
	],
	[
		"2026-04-17",
		"ES",
		"Short",
		3,
		5235.5,
		5229.25,
		937.5,
		540,
		"VWAP rejection",
		"Clean rejection after failed high."
	],
	[
		"2026-04-18",
		"NQ",
		"Long",
		2,
		18512,
		18493,
		-760,
		520,
		"Opening range",
		"Late entry after extension."
	],
	[
		"2026-04-18",
		"NQ",
		"Long",
		4,
		18498.5,
		18484.25,
		-1140,
		600,
		"Breakout continuation",
		"Added size after first loss."
	],
	[
		"2026-04-21",
		"CL",
		"Short",
		2,
		81.24,
		80.92,
		640,
		460,
		"Level reclaim",
		"Oil inventory fade."
	],
	[
		"2026-04-21",
		"NQ",
		"Short",
		1,
		18420.75,
		18406,
		295,
		350,
		"VWAP rejection",
		"Reduced size into chop."
	],
	[
		"2026-04-22",
		"ES",
		"Long",
		4,
		5216.25,
		5211.75,
		-900,
		500,
		"Breakout continuation",
		"Breakout failed under prior high."
	],
	[
		"2026-04-22",
		"ES",
		"Long",
		6,
		5214.75,
		5209.5,
		-1575,
		650,
		"Breakout continuation",
		"Size exceeded plan."
	],
	[
		"2026-04-23",
		"GC",
		"Long",
		1,
		2398.1,
		2407.4,
		930,
		420,
		"Level reclaim",
		"Held through retest."
	],
	[
		"2026-04-24",
		"NQ",
		"Short",
		3,
		18610.5,
		18620.75,
		-615,
		510,
		"VWAP rejection",
		"Invalidation respected."
	],
	[
		"2026-04-24",
		"NQ",
		"Short",
		3,
		18618,
		18629.25,
		-675,
		500,
		"VWAP rejection",
		"Second attempt was lower quality."
	],
	[
		"2026-04-24",
		"NQ",
		"Short",
		5,
		18625,
		18638.5,
		-1350,
		650,
		"Opening range",
		"Third attempt after two losses."
	],
	[
		"2026-04-25",
		"ES",
		"Short",
		2,
		5254.75,
		5248.25,
		650,
		420,
		"Opening range",
		"Smaller size after drawdown."
	],
	[
		"2026-04-28",
		"NQ",
		"Long",
		2,
		18704.25,
		18726.75,
		900,
		520,
		"Opening range",
		"Good stop discipline."
	],
	[
		"2026-04-28",
		"NQ",
		"Long",
		2,
		18735,
		18745.25,
		410,
		450,
		"Breakout continuation",
		"Scaled quickly near target."
	],
	[
		"2026-04-29",
		"CL",
		"Long",
		1,
		80.44,
		80.07,
		-370,
		360,
		"Level reclaim",
		"No follow-through."
	],
	[
		"2026-04-30",
		"GC",
		"Short",
		1,
		2412.5,
		2402.9,
		960,
		430,
		"VWAP rejection",
		"Best execution of week."
	],
	[
		"2026-05-01",
		"ES",
		"Long",
		3,
		5260.25,
		5256.75,
		-525,
		390,
		"Opening range",
		"No second entry taken."
	],
	[
		"2026-05-01",
		"NQ",
		"Long",
		2,
		18820.5,
		18843.75,
		930,
		510,
		"Level reclaim",
		"Followed higher low."
	],
	[
		"2026-05-04",
		"NQ",
		"Short",
		3,
		18880,
		18861.25,
		1125,
		540,
		"VWAP rejection",
		"Let winner reach planned target."
	],
	[
		"2026-05-04",
		"ES",
		"Short",
		2,
		5282,
		5278,
		400,
		340,
		"VWAP rejection",
		"Partial near prior low."
	],
	[
		"2026-05-05",
		"NQ",
		"Long",
		4,
		18905.5,
		18897.75,
		-620,
		500,
		"Breakout continuation",
		"Small false break."
	],
	[
		"2026-05-05",
		"NQ",
		"Long",
		4,
		18900,
		18888.25,
		-940,
		520,
		"Breakout continuation",
		"Repeated setup without confirmation."
	],
	[
		"2026-05-06",
		"GC",
		"Long",
		1,
		2421.7,
		2430.3,
		860,
		390,
		"Level reclaim",
		"Clean reclaim after London low."
	],
	[
		"2026-05-06",
		"NQ",
		"Short",
		2,
		18862.5,
		18850,
		500,
		440,
		"Opening range",
		"Stopped trading after target window."
	]
].map(([date, market, side, contracts, entry, exit, pnl, risk, setup, notes], index) => ({
	id: `demo-${index + 1}`,
	date: String(date),
	market: String(market),
	side,
	contracts: Number(contracts),
	entry: Number(entry),
	exit: Number(exit),
	pnl: Number(pnl),
	risk: Number(risk),
	setup: String(setup),
	notes: String(notes)
}));
//#endregion
//#region src/lib/tradovateHistory.ts
function tradeAccountKey(trade) {
	if (trade.manual && !trade.source) return trade.manual.accountKey;
	return trade.source?.provider === "Rithmic" ? `Rithmic:${trade.source.accountKey}:${trade.source.accountId}` : trade.source ? `Tradovate:${trade.source.accountId}` : "local";
}
//#endregion
//#region src/lib/workspaceValidation.ts
var WORKSPACE_DISCLOSURE = "workspace-cloud-v1";
var uuid = (x) => typeof x === "string" && /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x);
var object = (x) => !!x && typeof x === "object" && !Array.isArray(x) && Object.getPrototypeOf(x) === Object.prototype;
var text = (x, max, min = 0) => typeof x === "string" && x.length >= min && x.length <= max;
var finite = (x) => typeof x === "number" && Number.isFinite(x) && Math.abs(x) <= 0x5af3107a4000;
var exact = (x, keys) => Object.keys(x).every((k) => keys.includes(k));
var account = (x) => text(x, 240, 1) && (x === "local" || isManualAccountKey(x) || x === "all" || /^Tradovate:[1-9]\d{0,15}$/.test(x) || /^Rithmic:[A-Za-z0-9_-]{20,64}:[^\x00-\x1f]{1,128}$/.test(x));
var date = (x) => typeof x === "string" && /^20\d\d-\d\d-\d\d$/.test(x) && Number.isFinite(Date.parse(x + "T00:00:00Z")) && (/* @__PURE__ */ new Date(x + "T00:00:00Z")).toISOString().slice(0, 10) === x;
function validTrade(t) {
	if (!object(t) || !exact(t, [
		"id",
		"date",
		"market",
		"side",
		"contracts",
		"entry",
		"exit",
		"pnl",
		"risk",
		"riskStatus",
		"setup",
		"notes",
		"manual",
		"source"
	]) || !text(t.id, 240, 1) || t.id.startsWith("demo-") || !text(t.date, 40, 10) || !date(t.date.slice(0, 10)) || !Number.isFinite(Date.parse(t.date)) || !text(t.market, 80, 1) || !["Long", "Short"].includes(t.side) || !finite(t.contracts) || t.contracts <= 0 || ![
		"entry",
		"exit",
		"pnl",
		"risk"
	].every((k) => finite(t[k])) || t.risk < 0 || !text(t.setup, 2e3) || !text(t.notes, 1e4) || t.riskStatus !== void 0 && !["provided", "missing"].includes(t.riskStatus)) return false;
	if (t.manual !== void 0 && (!object(t.manual) || !exact(t.manual, [
		"accountKey",
		"currency",
		"pnlBasis"
	]) || !t.id.startsWith("manual-") || !account(t.manual.accountKey) || t.manual.accountKey === "all" || t.manual.currency !== "USD" || !["gross_before_fees", "reported_net"].includes(t.manual.pnlBasis) || t.source !== void 0)) return false;
	if (t.source !== void 0) {
		const s = t.source;
		if (!object(s)) return false;
		if (s.provider === "Tradovate") {
			if (!exact(s, [
				"provider",
				"accountId",
				"openedAt",
				"closedAt",
				"timeZone",
				"pnlBasis"
			]) || !/^\d{1,16}$/.test(s.accountId) || !t.id.startsWith("tradovate-" + s.accountId + ":") || s.pnlBasis !== void 0 && s.pnlBasis !== "gross_before_fees" || s.timeZone !== void 0 && s.timeZone !== "UTC" || ["openedAt", "closedAt"].some((k) => s[k] !== void 0 && (!text(s[k], 40) || !Number.isFinite(Date.parse(s[k]))))) return false;
		} else if (s.provider === "Rithmic") {
			if (!exact(s, [
				"provider",
				"accountKey",
				"accountId",
				"currency"
			]) || !account(`Rithmic:${s.accountKey}:${s.accountId}`) || !text(s.currency, 8, 1)) return false;
		} else return false;
	}
	return true;
}
function validRules(r) {
	return Array.isArray(r) && r.length <= 64 && new Set(r.map((v) => v?.id)).size === r.length && r.every((v) => object(v) && exact(v, [
		"id",
		"name",
		"metric",
		"limit",
		"severity",
		"enabled"
	]) && text(v.id, 100, 1) && text(v.name, 200, 1) && [
		"maxDailyLoss",
		"maxTradeLoss",
		"maxContracts",
		"maxLossStreak",
		"minProfitFactor",
		"minAvgR"
	].includes(v.metric) && finite(v.limit) && v.limit >= 0 && [
		"critical",
		"warning",
		"info"
	].includes(v.severity) && typeof v.enabled === "boolean");
}
function assertValue(v, deleted = false) {
	if (!object(v) || ![
		"trade",
		"rules",
		"daily_note",
		"account",
		"broker_cash"
	].includes(v.kind) || !text(v.recordId, 240, 1) || !account(v.accountId) || v.schemaVersion !== 1 || !object(v.payload) || JSON.stringify(v.payload).length > 21e5) throw Error("Invalid workspace record.");
	if (deleted) {
		if (Object.keys(v.payload).length) throw Error("Deletion payload must be empty.");
		return;
	}
	const p = v.payload;
	let valid = false;
	if (v.kind === "trade") valid = validTrade(p) && p.id === v.recordId && tradeAccountKey(p) === v.accountId;
	if (v.kind === "rules") valid = v.recordId === "current" && v.accountId === "all" && exact(p, ["rules"]) && validRules(p.rules);
	if (v.kind === "daily_note") valid = exact(p, [
		"date",
		"note",
		"tradeId"
	]) && date(p.date) && text(p.note, 2e3) && (p.tradeId === null || text(p.tradeId, 240, 1)) && v.recordId === JSON.stringify([v.accountId, p.date]);
	if (v.kind === "account") valid = v.accountId !== "all" && v.recordId === v.accountId && exact(p, ["name"]) && text(p.name, 128, 1) && !/[\x00-\x1f\x7f]/.test(p.name);
	if (v.kind === "broker_cash") valid = exact(p, ["cash", "fingerprint"]) && object(p.cash) && text(p.fingerprint, 2e6) && v.recordId === v.accountId && v.accountId.startsWith("Tradovate:");
	if (!valid) throw Error("Unsupported or invalid workspace payload. Original data is retained.");
}
function assertWrites(rows, maximum = 500) {
	if (!Array.isArray(rows) || rows.length < 1 || rows.length > maximum) throw Error("Invalid number of workspace changes.");
	const seen = /* @__PURE__ */ new Set();
	for (const r of rows) {
		assertValue(r, !!r?.deleted);
		if (!exact(r, [
			"kind",
			"recordId",
			"accountId",
			"schemaVersion",
			"payload",
			"expectedRevision",
			"deleted",
			"recreateDailyNote"
		]) || !Number.isSafeInteger(r.expectedRevision) || r.expectedRevision < 0 || typeof r.deleted !== "boolean" || "recreateDailyNote" in r && (r.recreateDailyNote !== true || r.kind !== "daily_note" || r.deleted || r.expectedRevision < 1) || r.kind === "broker_cash" && !r.deleted) throw Error("Invalid workspace change.");
		const k = JSON.stringify([r.kind, r.recordId]);
		if (seen.has(k)) throw Error("Duplicate workspace change.");
		seen.add(k);
	}
}
function assertRecords(rows) {
	if (!Array.isArray(rows)) throw Error("Invalid workspace snapshot.");
	const seen = /* @__PURE__ */ new Set();
	for (const r of rows) {
		assertValue(r, !!r?.deletedAt);
		if (!exact(r, [
			"kind",
			"recordId",
			"accountId",
			"schemaVersion",
			"payload",
			"revision",
			"createdAt",
			"updatedAt",
			"deletedAt"
		]) || !Number.isSafeInteger(r.revision) || r.revision < 1 || ![r.createdAt, r.updatedAt].every((x) => typeof x === "string" && Number.isFinite(Date.parse(x))) || r.deletedAt !== null && (typeof r.deletedAt !== "string" || !Number.isFinite(Date.parse(r.deletedAt)))) throw Error("Invalid workspace snapshot.");
		const k = JSON.stringify([r.kind, r.recordId]);
		if (seen.has(k)) throw Error("Duplicate workspace identity.");
		seen.add(k);
	}
}
//#endregion
//#region server/workspace.ts
var WorkspaceOperationRejection = class extends ApiError {
	rejectedOperationId;
	rejectionCode;
	constructor(status, message, rejectedOperationId, rejectionCode) {
		super(status, message);
		this.rejectedOperationId = rejectedOperationId;
		this.rejectionCode = rejectionCode;
	}
};
function assertWorkspaceProject(env) {
	const ref = env.WORKSPACE_SYNC_PROJECT_REF;
	if (!ref || !/^[a-z0-9]{20}$/.test(ref) || ![`https://${ref}.supabase.co`, `https://${ref}.supabase.co/`].includes(env.SUPABASE_URL || "")) throw new ApiError(503, "Account storage project is not configured correctly.");
}
async function workspaceRest(path, options = {}) {
	const base = String(process.env.SUPABASE_URL || "").replace(/\/$/, "");
	const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
	if (!base || !key) throw new ApiError(503, "Account storage is unavailable.");
	const url = new URL(base + "/rest/v1/" + path);
	for (const [k, v] of Object.entries(options.query || {})) url.searchParams.set(k, String(v));
	const response = await fetch(url, {
		method: options.body === void 0 ? "GET" : "POST",
		headers: supabaseServiceHeaders(key, { ...options.prefer ? { Prefer: options.prefer } : {} }),
		body: options.body === void 0 ? void 0 : JSON.stringify(options.body),
		signal: AbortSignal.timeout(15e3)
	});
	const data = await response.json();
	if (!response.ok) {
		const message = String(data?.message || "");
		if ([
			"revision_conflict",
			"deleted_record",
			"trade_account_changed",
			"missing_delete_target"
		].includes(message)) throw new WorkspaceOperationRejection(409, "A newer change exists. Review the account copy before saving.", options.body?.p_operation, message);
		if (/incomplete_other_batch|missing_batch_start/.test(message)) throw new ApiError(423, "An account copy is incomplete. Resume its original browser.");
		if (message === "consent_required") throw new ApiError(403, "Enable account storage first.");
		if (message === "trade_cap_exceeded") throw new WorkspaceOperationRejection(422, "Your saved trade limit would be exceeded. Correct your browser copy and reload to review.", options.body?.p_operation, message);
		throw new ApiError(503, "Account storage is unavailable.");
	}
	return data;
}
function createWorkspaceHandler({ auth = requirePolicyAcceptedUser, rest = workspaceRest, enabled = () => process.env.WORKSPACE_SYNC_ENABLED === "true", environment = () => process.env } = {}) {
	return async (req, res) => {
		res.setHeader("Cache-Control", "private, no-store");
		if (!enabled()) return res.status(404).json({ error: "Account storage is not enabled." });
		try {
			assertWorkspaceProject(environment());
			if (!["GET", "POST"].includes(req.method)) {
				res.setHeader("Allow", "GET, POST");
				return res.status(405).json({ error: "Method not allowed" });
			}
			const user = await auth(req);
			if (!uuid(user.id)) throw new ApiError(401, "Sign in again.");
			let body = req.method === "GET" ? void 0 : req.body;
			if (typeof body === "string") {
				if (Buffer.byteLength(body) > 4e6) throw new ApiError(413, "Too many changes for one request.");
				try {
					body = JSON.parse(body);
				} catch {
					throw new ApiError(400, "Invalid request.");
				}
			}
			if (body && Buffer.byteLength(JSON.stringify(body)) > 4e6) throw new ApiError(413, "Too many changes for one request.");
			const url = new URL(req.url || "/api/workspace", "https://cova.invalid");
			if ((req.method === "GET" ? url.searchParams.get("owner") : body?.owner) !== user.id) throw new ApiError(409, "Your session changed. Sign in again.");
			const settings = async () => {
				const rows = await rest("workspace_settings", { query: {
					owner_id: "eq." + user.id,
					select: "disclosure_version,revision,pending_manifest",
					limit: "1"
				} });
				if (!Array.isArray(rows)) throw Error("Invalid settings");
				return rows[0] || null;
			};
			if (req.method === "GET") {
				const offset = Number(url.searchParams.get("offset") || "0");
				const byteOffset = Number(url.searchParams.get("byteOffset") || "0");
				const expected = url.searchParams.get("revision");
				if (!Number.isSafeInteger(offset) || offset < 0 || !Number.isSafeInteger(byteOffset) || byteOffset < 0 || expected !== null && (!/^\d+$/.test(expected) || !Number.isSafeInteger(Number(expected))) || (offset || byteOffset) && expected === null) throw new ApiError(400, "Invalid snapshot cursor.");
				const before = await settings();
				const revision = before?.revision || 0;
				if (expected !== null && Number(expected) !== revision) throw new ApiError(409, "Account changed while loading. Retry.");
				if (before?.pending_manifest) return res.status(200).json({
					owner: user.id,
					consent: true,
					pendingWrite: before.pending_manifest,
					revision,
					chunk: "",
					next: null
				});
				const page = await rest("workspace_records", { query: {
					owner_id: "eq." + user.id,
					select: "kind,record_id,account_id,schema_version,payload,revision,created_at,updated_at,deleted_at",
					order: "kind.asc,record_id.asc",
					limit: "250",
					offset: String(offset)
				} });
				if (!Array.isArray(page)) throw Error("Invalid page");
				const records = page.map((r) => ({
					kind: r.kind,
					recordId: r.record_id,
					accountId: r.account_id,
					schemaVersion: r.schema_version,
					payload: r.payload,
					revision: r.revision,
					createdAt: r.created_at,
					updatedAt: r.updated_at,
					deletedAt: r.deleted_at
				}));
				assertRecords(records);
				const encoded = Buffer.from(records.map((r) => JSON.stringify(r) + "\n").join(""));
				if (byteOffset > encoded.length) throw new ApiError(400, "Invalid snapshot cursor.");
				const end = Math.min(encoded.length, byteOffset + 1048576);
				const next = end < encoded.length ? {
					offset,
					byteOffset: end
				} : page.length ? {
					offset: offset + page.length,
					byteOffset: 0
				} : null;
				const after = await settings();
				if (JSON.stringify(before) !== JSON.stringify(after)) throw new ApiError(409, "Account changed while loading. Retry.");
				const result = {
					owner: user.id,
					consent: before?.disclosure_version === WORKSPACE_DISCLOSURE,
					pendingWrite: null,
					revision,
					chunk: encoded.subarray(byteOffset, end).toString("base64"),
					next
				};
				if (Buffer.byteLength(JSON.stringify(result)) > 15e5) throw Error("Snapshot page exceeds byte budget");
				return res.status(200).json(result);
			}
			if (body?.action === "consent") {
				if (body.disclosure !== "workspace-cloud-v1" || Object.keys(body).some((k) => ![
					"owner",
					"action",
					"disclosure"
				].includes(k))) throw new ApiError(400, "Confirm the account storage disclosure.");
				await rest("workspace_settings", {
					body: {
						owner_id: user.id,
						disclosure_version: WORKSPACE_DISCLOSURE
					},
					query: { on_conflict: "owner_id" },
					prefer: "resolution=ignore-duplicates,return=representation"
				});
				return res.status(200).json({
					owner: user.id,
					consent: true
				});
			}
			if (body?.action !== "apply" || !uuid(body.operationId) || Object.keys(body).some((k) => ![
				"action",
				"owner",
				"operationId",
				"records",
				"migration"
			].includes(k))) throw new ApiError(400, "Invalid save request.");
			try {
				assertWrites(body.records, 25e3);
				const m = body.migration;
				if (m !== void 0 && m !== null) {
					if (!m || typeof m !== "object" || !uuid(m.backupId) || !/^[a-f0-9]{64}$/.test(m.contentHash) || Object.keys(m).some((k) => ![
						"backupId",
						"contentHash",
						"batch",
						"totalBatches",
						"totalChanges"
					].includes(k))) throw Error();
					if (m.totalBatches !== void 0 && (!Number.isSafeInteger(m.totalBatches) || m.totalBatches < 2 || m.totalBatches > 2e4 || !Number.isSafeInteger(m.batch) || m.batch < 0 || m.batch >= m.totalBatches || !Number.isSafeInteger(m.totalChanges))) throw Error();
				}
			} catch {
				throw new ApiError(400, "Invalid workspace change. Originals remain in your browser.");
			}
			const hash = createHash("sha256").update(JSON.stringify({
				records: body.records,
				migration: body.migration ?? null
			})).digest("hex");
			const result = await rest("rpc/cova_apply_workspace_plan", { body: {
				p_owner: user.id,
				p_operation: body.operationId,
				p_hash: hash,
				p_records: body.records,
				p_migration: body.migration ?? null,
				p_max_trades: user.plan === "pro" ? null : 25
			} });
			assertRecords(result.records);
			return res.status(200).json({
				operationId: result.operationId,
				owner: user.id,
				records: [],
				applied: true
			});
		} catch (e) {
			if (e instanceof ApiError && e.rejectedOperationId) return res.status(e.statusCode).json({
				error: e.message,
				rejectedOperationId: e.rejectedOperationId,
				rejectionCode: e.rejectionCode
			});
			return sendApiError(res, e, "Account storage could not complete this request.");
		}
	};
}
var workspace_default = createWorkspaceHandler();
//#endregion
export { WorkspaceOperationRejection, assertWorkspaceProject, createWorkspaceHandler, workspace_default as default };
